#!/bin/sh

## Commandline param handling
IMPL=none
CONFIG=base

if [ -n "$1" ]; then
    IMPL="$1"
    shift
fi
if [ -n "$1" ]; then
    CONFIG="$1"
    shift
fi

## Git doesn't keep empty dirs
mkdir -p systems r6rs-libs

## Fetch packages required for running rcs42 and scripts/build.sps
echo "= Getting base systems"

if [ ! -d systems/srfi ]; then
    bzr checkout --lightweight \
        lp:~scheme-libraries-team/scheme-libraries/srfi systems/srfi
fi
for system in spells prometheus conjure; do
    if [ ! -d systems/$system ]; then
        git clone git://github.com/rotty/$system.git systems/$system
    fi
done

if [ "$IMPL" = none ]; then
    echo "No Scheme implemention specified, not setting up symlink tree."
    echo "[Note: You can use './scripts/launch IMPL symlink' to do so]"
    exit 0
fi

## Prepare symlink tree
echo "= Preparing symlink tree for $IMPL"
./scripts/launch "$IMPL" symlink

echo "= Fetching additional systems, using config '$CONFIG'"
./scripts/launch "$IMPL" ./systems/conjure/scripts/rcs42.sps \
    pull configs/"$CONFIG".cfg

echo "= Starting build using $IMPL"
./scripts/launch "$IMPL" build
