#!/bin/sh

#
# helpers
#

clean_symlink_tree() {
    if [ ! -d "$1" ]; then
	return
    fi
    dir="$1"; shift
    args=""
    while [ -n "$1" ]; do
	args="$args -a ! -name $1"; shift
    done
    findcmd="find $dir ! -type l -a ! -type d $args"
    if [ `$findcmd | wc -l` -ne 0 ]; then
	echo "tree $dir is dirty, aborting"
	exit 1
    fi
    rm -rf "$dir"
}

setup_no_symlinks() {
    impl="$1"; shift
    program="$1"; shift
    find systems -type f | awk -f scripts/build-liblist.awk -- $impl | $program "$@"
}

setup() {
    impl="$1"
    target_dir="targets/$impl"
    shift
    clean_symlink_tree "$target_dir" "*.slfasl"
    setup_no_symlinks $impl "$@" | while read source dest; do
	dest=`echo "$dest" | sed "s,^,$target_dir/,g"`
	if echo "$dest" | grep -q "\.sls$"; then
	    source_noext=`echo "$source" | sed "s,\.sls$,,g"`
	    for ext in ."$impl".sls .sls; do
		source="${source_noext}${ext}"
		if [ -f "$source" ]; then
		    echo "$source"
		    break
		fi
	    done
	fi
	mkdir -p `dirname "$dest"`
	ln -s "$source" "$dest"
    done
}

#
# implementation specific routines
#

launch_ikarus() {
    setup "ikarus" "ikarus --r6rs-script scripts/setup.scm symlinks"
    if [ $# -eq 0 ]; then
	cd targets/ikarus && rlwrap ikarus
    else
	cd targets/ikarus && ikarus --r6rs-script "$@"
    fi
}

launch_larceny() {
    setup_cmd="larceny -r6rs -path . -program scripts/setup.scm"
    if [ $# -eq 0 ]; then
	setup larceny "$setup_cmd" -- symlinks
	cd targets/larceny && rlwrap larceny -path . -err5rs
    elif [ "$1" = symlink ]; then
	setup larceny "$setup_cmd" -- symlinks
    elif [ "$1" = compile ]; then
	setup larceny "$setup_cmd" -- symlinks
	setup_no_symlinks larceny larceny -r6rs -path . -program scripts/setup.scm \
	    -- compile targets/larceny "(spe boot filesys) (larceny compiler)"
    elif [ "$1" = run ]; then
	shift
	if [ $# -eq 0 ]; then
	    cd targets/larceny && rlwrap larceny -path . -err5rs
	else
	    cd targets/larceny && larceny -path . -r6rs -program "$@"
	fi
    else
	cd targets/larceny && larceny -path . -r6rs -program "$@"
    fi
}

#
# main body follows
#

impl="$1"
if [ -z "$impl" ]; then
    echo "Usage: scripts/launch <impl> [<command> [<option> ...]]"
    exit 1
fi

case "$impl" in
    ikarus)
	launch=launch_ikarus
	;;
    larceny)
	launch=launch_larceny
	;;
    *) 
	echo "Unsupported implementation $impl; patches welcome"
	exit 1
	;;
esac
shift

set -e

[ -d "targets/$impl" ] || mkdir "targets/$impl"

$launch "$@"
