#!/bin/sh


#
# helpers
#

clean_symlink_tree() {
    if [ ! -d "$1" ]; then
	return
    fi
    dir="$1"; shift
    args=""
    while [ -n "$1" ]; do
	args="$args -a ! -name $1"; shift
    done
    findcmd="find $dir ! -type l -a ! -type d $args"
    if [ `$findcmd | tee ,log | wc -l` -ne 0 ]; then
	echo "tree $dir is dirty, aborting"
	exit 1
    fi
    rm -rf "$dir"
}

setup_no_symlinks() {
    program="$1"; shift
    (   echo "("
	for system in systems/*; do
	    find "$system" -name "*.sls" -a ! -path "*/_darcs/*" -printf "(\"${system}\""' "%p")\n'
	done
	echo ")"
    ) | $program "$@"
}

setup() {
    target_dir="$1"
    shift
    clean_symlink_tree "$target_dir" "*.slfasl"
    setup_no_symlinks "$@" | while read source dest; do
	dest=`echo "$dest" | sed "s,^,$target_dir/,g"`
	mkdir -p `dirname $dest`
	ln -s "$source" "$dest"
    done
}

#
# implementation specific routines
#

launch_ikarus() {
    setup "targets/ikarus" "ikarus --r6rs-script scripts/setup.scm symlinks"
    cd targets/ikarus && rlwrap ikarus "$@"
}

launch_larceny() {
    setup_cmd="larceny -r6rs -path . -program scripts/setup.scm"
    if [ $# -eq 0 ]; then
	setup targets/larceny "$setup_cmd" -- symlinks
	cd targets/larceny && rlwrap larceny -path . -err5rs
    elif [ "$1" = compile ]; then
	setup targets/larceny "$setup_cmd" -- symlinks
	setup_no_symlinks larceny -r6rs -path . -program scripts/setup.scm \
	    -- compile targets/larceny "(spe boot filesys) (larceny compiler)"
    elif [ "$1" = run ]; then
	shift
	if [ $# -eq 0 ]; then
	    cd targets/larceny && rlwrap larceny -path . -err5rs
	else
	    cd targets/larceny && larceny -path . -r6rs -program "$@"
	fi
    fi
}

#
# main body follows
#

impl="$1"
if [ -z "$impl" ]; then
    echo "Usage: scripts/launch <impl> [<command> [<option> ...]]"
    exit 1
fi

case "$impl" in
    ikarus)
	launch=launch_ikarus
	;;
    larceny)
	launch=launch_larceny
	;;
    *) 
	echo "Unsupported implementation $impl; patches welcome"
	exit 1
	;;
esac
shift

set -e

[ -d "targets/$impl" ] || mkdir "targets/$impl"

if [ `ls systems | wc -l` -ne 0 ]; then
    $setup
fi

$launch "$@"
